server:
  port: 18080

spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848    #修改本机的host文件对应ip
        group: qudaotong
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # admin-server   ADMIN_SERVICE   ->   转发到微服务(ADMIN_SERVICE)
      routes:
        - id: admin-server-router
          uri: lb://admin-server           #转发到哪个目的地
          predicates:
            - Path=/admin/**
          filters:
            - StripPrefix=1

        - id: member-server-router
          uri: lb://member-server         #转发到哪个目的地
          predicates:
            - Path=/member/**
          filters:
            - StripPrefix=1

        - id: project-server-router
          uri: lb://project-server          #转发到哪个目的地
          predicates:
            - Path=/project/**
          filters:
            - StripPrefix=1

        - id: basic-data-server-router
          uri: lb://data-server          #转发到哪个目的地
          predicates:
            - Path=/data/**
          filters:
            - StripPrefix=1

        - id: search-server-router
          uri: lb://search-server          #转发到哪个目的地
          predicates:
            - Path=/search/**
          filters:
            - StripPrefix=1

    # 通过网关来完成对两种维度的限流：网关维度+API分组
    sentinel:
      transport:
        dashboard: sentinel-server:8858
      datasource:
        #        ds1.file:
        #          file: classpath:gw-flow.json    # 网关+API分组的限流
        #          ruleType: gw_flow
        #
        #        ds2.file:
        #          file: classpath:api-group.json
        #          ruleType: gw_api_group
        # com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource 使用navos持久化我们的sentinel数据时，需要添加nacos-datasource依赖
        ds1.nacos:
          serverAddr: nacos-server:8848
          dataId: gw-flow
          ruleType: gw_flow
        ds2.nacos:
          serverAddr: nacos-server:8848
          dataId: api-group
          ruleType: gw_api_group
  # 我们演示了sentinel-dashboard 的规则的定义，而且规则定义好了后，我们的网关能立马感知到（生效）(nacos无法感知)，但是我们下次重启，会丢失规则
  redis:
    host: redis-server
    port: 6379
    database: 2